name: Preview Deployment

on:
  pull_request:
    branches:
      - preview
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run linting
        run: bun run lint

  deploy-preview:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: preview
    steps:
      # Thêm checkout step
      - uses: actions/checkout@v4
        
      - name: Deploy to Render
        uses: Bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          retries: 20
          wait: 16000
          sleep: 30000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}