name: Preview Deployment

on:
  pull_request:
    branches:
      - preview
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run linting
        run: bun run lint

  deploy-preview:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: preview
    steps:
      - name: Deploy to Render
        id: deploy
        run: |
          curl -X POST \
          "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "accept: application/json" \
          -H "authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "content-type: application/json"