name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Thêm bước cài đặt Bun
      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run linting
        run: bun run lint
        
      # Uncomment if you have tests
      # - name: Run tests
      #   run: bun test

  # deploy-production:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: production
  #     url: ${{ steps.deploy.outputs.url }}
  #   steps:
  #     - name: Deploy to Render
  #       id: deploy
  #       uses: johnbeynon/render-deploy-action@v0.0.8
  #       with:
  #         service-id: ${{ secrets.RENDER_SERVICE_ID }}
  #         api-key: ${{ secrets.RENDER_API_KEY }}